In [2]:
import numpy as np


In [3]:
arr1 = [[1,2,3], [4,5,6], [7,8,9]]
display(arr1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
print(arr1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [3]:
np.array(arr1) #Dimensi antar list harus sama, misal semuanya harus 3 elemen, gabisa ada 1 list yang 4 elemen

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,11,2) #np.arange(index awal, index akhir, selisih)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
arr = np.arange(25)

In [9]:
randarr = np.random.randint(0,50,10) #Cari 10 angka random di range 0-49

#randint maksudnya random integer

In [10]:
arr.reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [11]:
randarr.max()

40

In [12]:
randarr.min()

3

In [13]:
randarr.argmax() #Mengecek nilai maksimal pada suatu array itu ada di indeks keberapa

1

In [14]:
for n, i in enumerate(randarr):
    print(f'Nilai {i} ada di indeks {n}')

Nilai 31 ada di indeks 0
Nilai 40 ada di indeks 1
Nilai 14 ada di indeks 2
Nilai 3 ada di indeks 3
Nilai 8 ada di indeks 4
Nilai 17 ada di indeks 5
Nilai 23 ada di indeks 6
Nilai 15 ada di indeks 7
Nilai 38 ada di indeks 8
Nilai 20 ada di indeks 9


In [15]:
np.zeros((2,3)) #Bikin matriks nilai 0 dengan ukuran 2 x 3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros(3) #Bikin array nilai 0 dengan panjang 3

array([0., 0., 0.])

In [17]:
np.ones((2,4)) #Bikin matriks nilai 1 dengan ukuran 2 x 4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.ones(5) #Bikin array nilai 1 dengan panjang 5

array([1., 1., 1., 1., 1.])

In [19]:
np.linspace(0, 10, 5)  #Hitung dari 0 sampai 10 dengan 5 angka berurutan dengan selisih antar nilai yang sama

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.linspace(9, 10, 20) #Hitung dari 9 sampai 10 dengan 20 angka berurutan dengan selisih antar nilai yang sama

array([ 9.        ,  9.05263158,  9.10526316,  9.15789474,  9.21052632,
        9.26315789,  9.31578947,  9.36842105,  9.42105263,  9.47368421,
        9.52631579,  9.57894737,  9.63157895,  9.68421053,  9.73684211,
        9.78947368,  9.84210526,  9.89473684,  9.94736842, 10.        ])

In [21]:
np.eye(5) #Buat matriks identitas dengan ukuran 5 x 5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(5,5) #Cari angka random (Baik itu float maupun integer) kemudian buat matriks berukuran 5 x 5, hanya boleh positif

array([[0.02168163, 0.45494838, 0.93177737, 0.45249897, 0.43440624],
       [0.17047529, 0.22380345, 0.5963083 , 0.06861659, 0.77600334],
       [0.54692672, 0.27318207, 0.53480449, 0.40079051, 0.29678135],
       [0.99576013, 0.82222629, 0.50692457, 0.38994385, 0.17054015],
       [0.19692021, 0.42140364, 0.75406202, 0.24542185, 0.48942879]])

In [23]:
np.random.randn(10, 4) #Cari angka random (Baik itu float maupun integer) kemudian buat matriks berukuran 10 x 4, boleh negatif maupun positif

array([[ 0.89805398, -0.65438581, -0.31414016, -0.60526   ],
       [ 1.39601976,  0.37296764,  1.39133511,  0.82436052],
       [-1.0988467 ,  0.18464388,  1.01875609,  1.15417646],
       [ 0.36298657, -0.52061991, -0.78459324, -0.41200821],
       [-0.08332867,  0.05292047, -1.77404794,  0.04197543],
       [-0.31439223,  1.31458225,  0.57100441,  0.64325592],
       [ 0.24354562,  0.35116825,  0.57478594, -1.12784209],
       [-0.34155554,  0.31781486,  0.60273499,  1.69965825],
       [ 0.39886484, -1.06144272, -1.65246783,  0.68079077],
       [ 1.77895669,  1.16009049, -1.0242454 , -0.60530868]])

In [24]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [25]:
np.arange(1,100,(100/20))

array([ 1.,  6., 11., 16., 21., 26., 31., 36., 41., 46., 51., 56., 61.,
       66., 71., 76., 81., 86., 91., 96.])

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#Menampilkan isi dari elemen berdasarkan index

display(arr[8],
        arr[7:10]) # Indeks ke 8 sampai 10

8

array([7, 8, 9])

In [31]:
#Mengganti nilai dari elemen berdasarkan index

display(arr)
arr[0] = 100
display(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [34]:
#Slicing

slice_of_arr = arr[2:6]
display(slice_of_arr)

array([2, 3, 4, 5])

In [35]:
# Mengganti semua nilai dari elemen berdasarkan index
display(slice_of_arr)
slice_of_arr[:] = 99
display(slice_of_arr)

array([2, 3, 4, 5])

array([99, 99, 99, 99])

In [37]:

arr_copy = arr.copy()

arr_copy[:] = 100
display(arr_copy)
display(arr)

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

array([100,   1,  99,  99,  99,  99,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [39]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
display(arr_2d)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
arr_2d[0][0]

5

In [41]:
arr_2d[0][2]

15

In [58]:
display(arr_2d[:2],
        arr_2d[:,1:]) #Menampilkan array ke 0 sampai 1 dan elemen ke 1 sampai 2

array([[ 5, 10, 15],
       [20, 25, 30]])

array([[10, 15],
       [25, 30],
       [40, 45]])

In [54]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [59]:
arr_50 = np.arange(1,51)
arr_50

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [61]:
arr_50.reshape(25, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30],
       [31, 32],
       [33, 34],
       [35, 36],
       [37, 38],
       [39, 40],
       [41, 42],
       [43, 44],
       [45, 46],
       [47, 48],
       [49, 50]])